---
- apt_repository:
   repo: 'ppa:openjdk-r/ppa'

- name: Install Java
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - 'openjdk-8-jre'
    - 'openjdk-8-jdk'

- name: Create Jenkins User
  user:
    name: jenkins
    state: present
    home: '/home/jenkins'

- name: Download Swarm Client
  get_url:
    url: '{{ jenkins_swarm_client }}'
    dest: '/home/jenkins/swarm.jar'

- name: Configure Jenkins-Slave service
  template:
    src: 'Debian/jenkins-slave.service.j2'
    dest: '/etc/systemd/system/jenkins-slave.service'

- name: Start Jenkins-Slave
  service:
    name: 'jenkins-slave'
    state: started
